#!/bin/sh

MIRROR1=ftp://ftp.freebsd.org

x=`jot -r 1 1 115`
# echo $x
x=MIRROR${x}
eval : \$\{MIRROR=\$${x}\}

_UNAME_R=`uname -r`
_UNAME_R=${_UNAME_R%-p*}

case ${_UNAME_R} in
  *-CURRENT|*-STABLE|*-PRERELEASE)
    RELDIR="snapshots"
    ;;
  *)
    RELDIR="releases"
    ;;
esac

#BSDINSTALL_DISTSITE="$MIRROR/pub/FreeBSD/${RELDIR}/`uname -m`/`uname -p`/${_UNAME_R}"
BSDINSTALL_DISTSITE="https://ci-01.nyi.hardenedbsd.org/pub/hardenedbsd/13-stable/amd64/amd64/BUILD-LATEST/"
export BSDINSTALL_DISTSITE

echo $BSDINSTALL_DISTSITE
